"""empty message

Revision ID: 325487baaa6b
Revises: 0c166ce6298d
Create Date: 2024-04-30 15:22:35.842146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '325487baaa6b'
down_revision = '0c166ce6298d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('mother', sa.VARCHAR(length=50), nullable=True),
    sa.Column('father', sa.VARCHAR(length=50), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(), nullable=True),
    sa.Column('life_description', sa.VARCHAR(), nullable=True),
    sa.Column('married', sa.BOOLEAN(), nullable=False),
    sa.Column('married_to', sa.VARCHAR(), nullable=True),
    sa.Column('children', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parent_child')
    op.drop_table('parent')
    op.drop_table('child')
    # ### end Alembic commands ###
