"""empty message

Revision ID: f549487a32e7
Revises: 245477d5581d
Create Date: 2024-04-30 16:52:32.519130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f549487a32e7'
down_revision = '245477d5581d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_id', sa.Integer(), nullable=True))
        batch_op.drop_column('mothid_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mothid_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('mother_id')

    # ### end Alembic commands ###
