"""empty message

Revision ID: 298926893ae4
Revises: d54393283a7e
Create Date: 2025-10-10 10:57:43.107554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298926893ae4'
down_revision = 'd54393283a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
