"""empty message

Revision ID: 3e3614289052
Revises: 
Create Date: 2024-04-24 19:45:15.806287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3614289052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mother', sa.String(length=50), nullable=True),
    sa.Column('father', sa.String(length=50), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('life_description', sa.String(), nullable=True),
    sa.Column('married', sa.Boolean(), nullable=False),
    sa.Column('married_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
