"""empty message

Revision ID: a08f38e286f5
Revises: 5bbad228f36e
Create Date: 2025-10-20 13:33:54.334101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08f38e286f5'
down_revision = '5bbad228f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('avatar_img',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=4000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('avatar_img',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
