"""empty message

Revision ID: ba2095a421dc
Revises: a006d8fad9b0
Create Date: 2025-09-30 11:45:22.613812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2095a421dc'
down_revision = 'a006d8fad9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=32), nullable=False))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
